### ISSUE TITLE
UnboundLocalError: local variable 'missing_cols' referenced before assignment`

### ISSUE THREAD

**Issue by r0bb23** [AutoViML/Auto_ViML#17]
I'm getting the following error:

`Filling missing values with "missing" placeholder and adding a column for missing_flags
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-20-d43a16739b75> in <module>
     12     Stacking_Flag=False,
     13     Imbalanced_Flag=True,
---> 14     verbose=2,
     15 )

/sas_cambrian/Projects/hamilton_attrib_276597/rxb427/python3_env/lib/python3.6/site-packages/autoviml/Auto_ViML.py in Auto_ViML(train, target, test, sample_submission, hyper_param, feature_reduction, scoring_parameter, Boosting_Flag, KMeans_Featurizer, Add_Poly, Stacking_Flag, Binning_Flag, Imbalanced_Flag, verbose)
    754                     preds.append(new_missing_col)
    755                     missing_flag_cols.append(new_missing_col)
--> 756             elif f in missing_cols:
    757                 #### YOu have to do nothing for missing column yet. Leave them as is for Iterative Imputer later ##############
    758                 continue

UnboundLocalError: local variable 'missing_cols' referenced before assignment`

I didn't have time to dig too deep in the code. But it does appear the missing_cols gets defined in an if statement that appears to be checking if the test dataset exist before it runs. So it appears there is a way that you can get to the 756 check without providing a test dataset.

So either the defining of the missing_cols needs to change or you need to fix the logical error that allows the `f in missing_cols` check. You could also just get rid of that check since it doesn't do anything right now.

**Comment by AutoViML** [comment]
Robert
I remember fixing this problem a few weeks ago. Are you sure you are using
the latest version? Can you please do a pip install autoviml —upgrade

Or can you please print the version number that you see on your screen when
you import AutoViML?

Thanks much
Ram

**Comment by r0bb23** [comment]
Version = 0.1.660

**Comment by AutoViML** [comment]
I have fixed this and uploading it right now. Should be in version 0.1.662 

Please download it or upgrade to it and confirm

pip install autoviml --upgrade --ignore-installed

Is one way to do the upgrade.
Thanks for your patience.
