### ISSUE TITLE
Training model errors out without context/stacktrace.

### ISSUE THREAD

**Issue by r0bb23** [AutoViML/Auto_ViML#18]
```
Training regular model first time is Erroring: Check if your Input is correct...
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-32-d59141079a76> in <module>
     12     Stacking_Flag=False,
     13     Imbalanced_Flag=False,
---> 14     verbose=0,
     15 )

TypeError: 'NoneType' object is not iterable
```

I DO think there is probably something wrong with the data I'm feeding in or how I'm feeding it in. However, The fact that only the error is printed and there is no context around where, what, etc. is erroring out is why I'm raising this to an issue. Its near impossible to figure out what is wrong with sparse information provided.

In short, you should probably surface the error from the training of the model here with the stacktrace.

**Comment by Rishav-hub** [comment]
Getting same issue while performing Regression

**Comment by AutoViML** [comment]
Hi @Rishav-hub 👍 
Closing this for now. Please re-open if this is still an issue.
