### ISSUE TITLE
memory issue while running multi label classification 

### ISSUE THREAD

**Issue by taknev83** [AutoViML/Auto_ViML#19]
Hi Ram,

I am trying multi label classification with the following parameters & encountering "Kernal tried to allocate more memory than available" error, while running in kaggle with memory of 16GB. The predictor in train is title & abstract of the book. Is there is any way to overcome this memory issue?

model, features, trainm, testm = Auto_ViML(
    train=train, 
    target=['Computer_Science', 'Physics', 'Mathematics', 'Statistics', 'Quantitative_Biology', 'Quantitative_Finance'], 
    test=test, 
    sample_submission=sample_submission, 
    hyper_param="GS", 
    feature_reduction=False,
    scoring_parameter="f1",
    KMeans_Featurizer=False,
    Boosting_Flag=True,
    Binning_Flag=True,
    Add_Poly=False,
    Stacking_Flag=False,
    Imbalanced_Flag=False,
    verbose=2,
)

![image](https://user-images.githubusercontent.com/61316462/90545176-4c9fac00-e199-11ea-84b7-bd3dfac4a8c0.png)

Thanks,
Venkatesh

**Comment by AutoViML** [comment]
I have fixed the problem in Auto_NLP. Can you please combine the title and
abstract columns into a single column (and then delete them) and then feed
the data set to Auto_NLP.
Make sure you use the latest version that's in the github by typing this
command in the Colab:
!pip install git+https://github.com/AutoViML/Auto_ViML.git

Then do this:
from autoviml.Auto_ViML import Auto_NLP

Then run Auto_NLP with the data set. It will run the whole thing and
provide you results.

Ram
