### ISSUE TITLE
Saving Model Weights

### ISSUE THREAD

**Issue by tanish36** [AutoViML/Auto_ViML#20]
Does anyone know which all model are being trained by Auto Viml and how to save the weights of the final trained model

**Comment by AutoViML** [comment]
Actually these are the following models that you can select from:
Linear: linear regression, logistic
Forests: Random Forest
Boosting: XGB, Catboost
Ensemble: it combines the above

There are no deep learning models - hence to no model trained weights.
R

**Comment by tanish36** [comment]
So if i want to add my deep learning model or any any other model like SVM model in AutoViml can i do it ?

**Comment by AutoViML** [comment]
Of course. Just submit a pull request once you create your module
Ram

**Comment by tanish36** [comment]
ok thank you
