### ISSUE TITLE
Is it possible to generate sklearn code 

### ISSUE THREAD

**Issue by notsinkingtitanic** [AutoViML/Auto_ViML#21]
Is it possible that after the call to `Auto_ViML` function, we generate `sklearn` python code which generate the same model that the `Auto_ViML` function produced? Or at least the architecture of the model so we can reproduce it in sklearn?  

Thank you.

**Comment by AutoViML** [comment]
Yes it should be possible - I am working on it. Will announce it in a few weeks. Watch this space.
