### ISSUE TITLE
UnboundLocalError: local variable 'cols' referenced before assignment

### ISSUE THREAD

**Issue by pakphump** [AutoViML/Auto_ViML#24]
I found the error from version 0.1.701 in Auto_ViML

UnboundLocalError: local variable 'cols' referenced before assignment

### After this, y_pred is a Series from now on. You need y_pred.values  ####
if len(cols) == 5:
print('    Calculating weighted average ensemble of %d classifiers' %len(new_cols))

It should be new_cols ?

**Comment by AutoViML** [comment]
Hi @pakphump 👍 
You are correct. That was a typo - it has been fixed. Just upgrade via:
```
pip install autoviml --upgrade
```
Please test and confirm,
AutoViML
