### ISSUE TITLE
ModuleNotFoundError: No module named 'lightgbm'

### ISSUE THREAD

**Issue by emsi** [AutoViML/Auto_ViML#25]
I've installed from pip. I'm using py 3.9.

When attempting:
```
train_x, test_x, final, predicted= Auto_NLP(input_feature, train, test,target,score_type="balanced_accuracy",top_num_features=100,modeltype="Classification", verbose=2, build_model=True)
```
I got:
```
[nltk_data]    | 
[nltk_data]  Done downloading collection popular

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Input In [35], in <cell line: 1>()
----> 1 train_x, test_x, final, predicted= Auto_NLP(input_feature, train, test,target,score_type="balanced_accuracy",top_num_features=100,modeltype="Classification", verbose=2, build_model=True)

File /usr/local/lib/python3.9/site-packages/autoviml/Auto_NLP.py:1334, in Auto_NLP(nlp_column, train, test, target, score_type, modeltype, top_num_features, verbose, build_model)
   1332 nltk.download("popular")
   1333 calibrator_flag = False
-> 1334 from lightgbm import LGBMClassifier, LGBMRegressor
   1335 seed = 99
   1336 train = copy.deepcopy(train)

ModuleNotFoundError: No module named 'lightgbm'
```

A missing dependency?

**Comment by AutoViML** [comment]
Hi @emsi 👍 Thanks for testing out AutoViML. I will add the lightGBM dependency when I roll out the next version. In the meantime, try pip installing lightgbm as a workaround in your machine.
Thanks
AutoViML

**Comment by emsi** [comment]
> Hi @emsi +1 Thanks for testing out AutoViML. I will add the lightGBM dependency when I roll out the next version. In the meantime, try pip installing lightgbm as a workaround in your machine. Thanks AutoViML

That's precisely what I did :)

**Comment by AutoViML** [comment]
@emsi 👍 
LightGBM has been added to requirements.txt and setup.py - this should work now. You can also create a pull request in these files in the future if you feel anything is missing.
Thanks
AutoViML Team
