### ISSUE TITLE
Problem with Auto_NLP: TypeError np.matrix is not supported

### ISSUE THREAD

**Issue by dlucredio** [AutoViML/Auto_ViML#30]
Hello,

I am trying to use Auto_NLP module of AutoViML, and I am facing an issue I don't know how to solve. Here are the files I am using to reproduce the problem.

- requirements.txt:

```
pandas==1.5.2
autoviml==0.1.710
lightgbm==3.3.4
lxml==4.9.2 
```
- train.csv: [dataset](https://raw.githubusercontent.com/kaustubhharapanahalli/twitter-sentiment-analysis/master/train.csv) with tweets with sentiment analysis I got from an [online paper about Auto_NLP](https://analyticsindiamag.com/hands-on-guide-to-using-autonlp-for-automating-sentiment-analysis/). To facilitate the test, you can keep only the 500 first lines of the file
 
- test_autonlp.ipynb: Jupyter notebook content, reproduced next:

```python
import pandas as pd
from sklearn.model_selection import train_test_split
from autoviml.Auto_NLP import Auto_NLP

data=pd.read_csv('train.csv')

train,test = train_test_split(data, test_size=0.2)

input_feature, target = "SentimentText", "Sentiment"

train["Sentiment"] = pd.to_numeric(train["Sentiment"])
test["Sentiment"] = pd.to_numeric(test["Sentiment"])

train_x, test_x, final, predicted=Auto_NLP(input_feature,train,test,target,score_type="balanced_accuracy",modeltype="classification",verbose=0,build_model=True)
```

I am getting the following error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[5], line 13
      9 input_feature, target = "SentimentText", "Sentiment"
     11 train["Sentiment"] = pd.to_numeric(train["Sentiment"])
---> 13 train_x, test_x, final, predicted=Auto_NLP(input_feature,train,test,target,score_type="balanced_accuracy",modeltype="classification",verbose=0,build_model=True)

File ~/.pyenv/versions/3.10.9/envs/testautonlp/lib/python3.10/site-packages/autoviml/Auto_NLP.py:1588, in Auto_NLP(nlp_column, train, test, target, score_type, modeltype, top_num_features, verbose, build_model)
   1582     calib_pipe = Pipeline([
   1583         ('tfidfvectorizer', best_vect),
   1584         ('convert_dense', FunctionTransformer(lambda x: x.todense(), accept_sparse=True)),
   1585         ('best_features', best_sel),
   1586          ])
   1587     best_model = CalibratedClassifierCV(best_estimator,cv=3, method='isotonic')
-> 1588     best_model.fit(calib_pipe.transform(X_train), y_train)
   1589     y_pred = best_model.predict(calib_pipe.transform(X_test))
   1590 else:

File ~/.pyenv/versions/3.10.9/envs/testautonlp/lib/python3.10/site-packages/sklearn/pipeline.py:659, in Pipeline.transform(self, X)
    657 Xt = X
    658 for _, _, transform in self._iter():
--> 659     Xt = transform.transform(Xt)
    660 return Xt

File ~/.pyenv/versions/3.10.9/envs/testautonlp/lib/python3.10/site-packages/sklearn/utils/_set_output.py:142, in _wrap_method_output.<locals>.wrapped(self, X, *args, **kwargs)
...
    743 xp, is_array_api = get_namespace(array)
    745 # store reference to original array to check if copy is needed when
[train.csv](https://github.com/AutoViML/Auto_ViML/files/10404796/train.csv)

    746 # function returns

TypeError: np.matrix is not supported. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
```

I am using Ubuntu with pyenv/virtualenv. I have tried Python 3.10 and 3.9, and also anaconda3-2022.10, but the error persists. Could it be something wrong in my environment setup? Or is it a bug?

**Comment by AutoViML** [comment]
@dlucredio 
thanks for trying out Auto_NLP 👍 

You must have something wrong in your environment since I am not getting any errors. I am running the latest version of Auto_NLP on Windows.
`Auto_ViML version: 0.1.710.`
`Auto_NLP version: 0.1.01`

Here is my notebook in zip format

[AUTO_NLP_Test.zip](https://github.com/AutoViML/Auto_ViML/files/10483509/AUTO_NLP_Test.zip)
Please let me know - if not close this issue.
Auto Vimal

**Comment by dlucredio** [comment]
You are correct! I had scikit-learn 1.2.0 installed in my environment. After doing a little research, I discovered that this error message was introduced in scikit-learn 1.1. So I changed my version to 1.0.2 and everything worked!

Thanks and congratulations on the great work
