### ISSUE TITLE
TypeError unexpected keyword argument 'base_estimator'

### ISSUE THREAD

**Issue by ticxx** [AutoViML/Auto_ViML#33]
Hello
I have a problem with the use of imbalanced-ensemble. In version 0.2.0 the parameter base_estimator was renamed to estimator. 
This leads to the following error:

```---------------------------------------------------------------------------
TypeError Traceback (most recent call last)
Cell In[4], line 1
----> 1 m, feats, trainm, testm = Auto_ViML(train, "purchase", "", "",
2 scoring_parameter="balanced_accuracy",
3 hyper_param='RS',feature_reduction=True,
4 Boosting_Flag=True,Binning_Flag=False,
5 Add_Poly=0, Stacking_Flag=False,
6 Imbalanced_Flag=True,
7 verbose=1)

File /opt/python/envs/minimal/lib/python3.8/site-packages/autoviml/Auto_ViML.py:1982, in Auto_ViML(train, target, test, sample_submission, hyper_param, feature_reduction, scoring_parameter, Boosting_Flag, KMeans_Featurizer, Add_Poly, Stacking_Flag, Binning_Flag, Imbalanced_Flag, GPU_flag, verbose)
1980 if Imbalanced_Flag:
1981 rf = RandomForestClassifier(n_estimators=100, random_state=99)
-> 1982 xgbm = SelfPacedEnsembleClassifier(base_estimator=rf, n_jobs=-1, soft_resample_flag=True)
1983 hyper_param = 'Imb'
1984 model_name = 'SPE'

File /opt/python/envs/minimal/lib/python3.8/site-packages/imbens/utils/_validation.py:604, in _deprecate_positional_args.<locals>.inner_f(*args, **kwargs)
597 warnings.warn(
598 f"Pass {', '.join(args_msg)} as keyword args. From version 0.9 "
599 f"passing these as positional arguments will "
600 f"result in an error",
601 FutureWarning,
602 )
603 kwargs.update({k: arg for k, arg in zip(sig.parameters, args)})
--> 604 return f(**kwargs)

TypeError: __init__() got an unexpected keyword argument 'base_estimator'
```

best regards and many thanks s

here the used version:
```
from autoviml.Auto_ViML import Auto_ViML

Imported Auto_ViML version: 0.1.713. Call using:
             m, feats, trainm, testm = Auto_ViML(train, target, test,
                            sample_submission='',
                            scoring_parameter='', KMeans_Featurizer=False,
                            hyper_param='RS',feature_reduction=True,
                             Boosting_Flag='CatBoost', Binning_Flag=False,
                            Add_Poly=0, Stacking_Flag=False,Imbalanced_Flag=False,
                            GPU_flag=False, verbose=1)
            

Imported Auto_NLP version: 0.1.01.. Call using:
     train_nlp, test_nlp, nlp_pipeline, predictions = Auto_NLP(
                nlp_column, train, test, target, score_type='balanced_accuracy',
                modeltype='Classification',top_num_features=200, verbose=0,
                build_model=True)
```

**Comment by AutoViML** [comment]
Hi @ticxx 
Thank you for trying out AutoViML and finding this bug 👍 

I have fixed it in the latest version. Just upgrade your version and you should be all set.

Thanks again,
Auto Vimal

**Comment by AutoViML** [comment]
This has been fixed. Please test with the latest version.    On Sunday, April 16, 2023 at 09:04:22 AM EDT, ticxx ***@***.***> wrote:  
 
 


Hello
I have a problem with the use of imbalanced-ensemble. In version 0.2.0 the parameter base_estimator was renamed to estimator.
This leads to the following error:
TypeError Traceback (most recent call last)
Cell In[4], line 1
----> 1 m, feats, trainm, testm = Auto_ViML(train, "purchase", "", "",
2 scoring_parameter="balanced_accuracy",
3 hyper_param='RS',feature_reduction=True,
4 Boosting_Flag=True,Binning_Flag=False,
5 Add_Poly=0, Stacking_Flag=False,
6 Imbalanced_Flag=True,
7 verbose=1)

File /opt/python/envs/minimal/lib/python3.8/site-packages/autoviml/Auto_ViML.py:1982, in Auto_ViML(train, target, test, sample_submission, hyper_param, feature_reduction, scoring_parameter, Boosting_Flag, KMeans_Featurizer, Add_Poly, Stacking_Flag, Binning_Flag, Imbalanced_Flag, GPU_flag, verbose)
1980 if Imbalanced_Flag:
1981 rf = RandomForestClassifier(n_estimators=100, random_state=99)
-> 1982 xgbm = SelfPacedEnsembleClassifier(base_estimator=rf, n_jobs=-1, soft_resample_flag=True)
1983 hyper_param = 'Imb'
1984 model_name = 'SPE'

File /opt/python/envs/minimal/lib/python3.8/site-packages/imbens/utils/_validation.py:604, in _deprecate_positional_args.<locals>.inner_f(*args, **kwargs)
597 warnings.warn(
598 f"Pass {', '.join(args_msg)} as keyword args. From version 0.9 "
599 f"passing these as positional arguments will "
600 f"result in an error",
601 FutureWarning,
602 )
603 kwargs.update({k: arg for k, arg in zip(sig.parameters, args)})
--> 604 return f(**kwargs)

TypeError: __init__() got an unexpected keyword argument 'base_estimator'

best regards and many thanks s

here the used version:
from autoviml.Auto_ViML import Auto_ViML

Imported Auto_ViML version: 0.1.713. Call using:
             m, feats, trainm, testm = Auto_ViML(train, target, test,
                            sample_submission='',
                            scoring_parameter='', KMeans_Featurizer=False,
                            hyper_param='RS',feature_reduction=True,
                             Boosting_Flag='CatBoost', Binning_Flag=False,
                            Add_Poly=0, Stacking_Flag=False,Imbalanced_Flag=False,
                            GPU_flag=False, verbose=1)
            

Imported Auto_NLP version: 0.1.01.. Call using:
     train_nlp, test_nlp, nlp_pipeline, predictions = Auto_NLP(
                nlp_column, train, test, target, score_type='balanced_accuracy',
                modeltype='Classification',top_num_features=200, verbose=0,
                build_model=True)
