### ISSUE TITLE
For sklearn above 1.0, the model. estimator didn't work, while 'base_estimator' worked.

### ISSUE THREAD

**Issue by JulesLiu** [AutoViML/Auto_ViML#36]
Well, maybe this is an issue that I should post in scikit-learn project?
I installed scikit-learn of 1.1:
   my modification for the codes:
![image](https://github.com/AutoViML/Auto_ViML/assets/60243348/1731229b-9f58-462f-8518-5a7e2014ae31)
  results and errors:
![Screenshot 2023-11-24 175528](https://github.com/AutoViML/Auto_ViML/assets/60243348/8f245bbb-2fb4-4c27-ba91-6f1bccfe8fbb)

For 1.3 of scikit-learn, the result is exactly same.
btw, my numpy is 1.26, I failed dozens of times to build the wheel for the ~1.19 version suggested in requirments.txt, but I doubt that this may affect sklearn CalibratedClassifierCV object's estimator attribute.

**Comment by JulesLiu** [comment]
The sklearn document says .estimator is new in version 1.2. Considered the results, the sklearn.__version__ 1.0.2 is the real version, which does not have this new feature, the pip-show is not the real version?
![image](https://github.com/AutoViML/Auto_ViML/assets/60243348/35c74008-fc08-4824-a239-744dae9475e2)

**Comment by AutoViML** [comment]
Hi @JulesLiu 
THANKS for trying out AutoViML 👍 
I have made a few minor changes to the code and the requirements.txt and setup.py files.
Can you please try one of these two install methods and see if it works:
```
pip install git+https://github.com/AutoViML/Auto_ViML.git
python3 -m pip install git+https://github.com/AutoViML/Auto_ViML.git
```
thanks again
Auto Vimal
