### ISSUE TITLE
How to let AutoViML know which column is ID, and also identify sub-class?

### ISSUE THREAD

**Issue by JulesLiu** [AutoViML/Auto_ViML#37]
Maybe I should split the issue into two?
Thanks to the contributors and previous issues, I finally made the program run to the end, but it seems that AutoViML didn't identify the column to mark different samples. I used 'Identifier' for the column, should I change it to another column name, or there is another method to pass this info to AutoViML?
![image](https://github.com/AutoViML/Auto_ViML/assets/60243348/0a6d39ab-6af8-4de4-a560-0b2af770e731)

Second question: I have two main classes: negative and positive, for positive, I want to split them into more classes based on how strong the positive feature is. For now, I assign 0 to negative, 1 to basic level of positive, and +0.2 for each level higher until reach 2. 
And AutoViML took them as 7 totally independent groups: 
![image](https://github.com/AutoViML/Auto_ViML/assets/60243348/9d1ec936-0562-44f9-82ab-93338cfc9de2)
What should I do to let AutoViML know that >1 is a large classification equal to  '0' group, and 1.2 1.4 1.6 ... are sub-groups? Another classification model?
BTW, if I solve the 1st problem, that is, AutoViML identifies different samples/IDs properly, the the  'shuffling the data set' will take one sample as a whole for shuffling, right?

**Comment by AutoViML** [comment]
Hi @JulesLiu 
Thanks for posting a second issue. 👍 
I am sorry you are having so many issues.
Let me try to answer your questions:
1. I try to identify the "ID" variable by seeing whether the number of unique values in that variable is equal to the number of rows in the data. If they match, then it's a unique ID variable. So if want to use ID, then it must meet the rule above.
2. I think you need to use two different models by first predicting the "positive" class and then building a mult-class model to split the "positive" class into more classes.

In terms of how we shuffle the dataset, it is based on the number of classes in the "y" variable.

Hope this helps
Auto Vimal

**Comment by JulesLiu** [comment]
@AutoViML Thanks for your reply! 
For 2, now I know what to do, that's very helpful.
But I'm still confused with the 'ID' problem. First, I want to make sure that the 'ID' we are talking about means the IDs for samples, right? For instances, the IDs for patients, celestial bodies or stocks?
Take the health research as an example, if I provided time series data from multiple patients, and want to build a model to predict disease onset (to the disease, not one specific patient), how should I organize the Train dataframe? What I did now, is as follows:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/bioli/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/bioli/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


index | ID (sample#) | Date | Feature1 | Feature2 | Target
-- | -- | -- | -- | -- | --
1 | 1 | 2023-01-01 |   |   | 0
2 | 1 | 2023-01-02 |   |   | 0
3 | 1 | 2023-01-03 |   |   | 1
… | … | … | … | … | …
56 | 2 | 2023-01-01 |   |   | 0
57 | 2 | 2023-01-02 |   |   | 0
58 | 2 | 2023-01-03 |   |   | 1
59 | 2 | 2023-01-04 |   |   | 1
… | … | … | … | … | …
108 | 3 | 2023-01-01 |   |   | 0
109 | 3 | 2023-01-02 |   |   | 0
110 | 3 | 2023-01-03 |   |   | 0



</body>

</html>
But according to your explanation, it seems that AutoViML won't take this ID as a mark/identifier for sample. And even I modify the AutoViML.py to mannually make the codes always load ['ID'] as ID column (or id_col in code?), I will only get an error since AutoViML will not accept one single sample with multiple rows, right?

**Comment by JulesLiu** [comment]
@AutoViML I'm sorry that I just found out that your team also has an Auto_TS  specialized in time-series data prediction, I'll switch to that one to see if I can handle it.

**Comment by AutoViML** [comment]
Ok @JulesLiu Let me know
